### ISSUE TITLE
Cannot capture jpeg/png from view

### ISSUE THREAD

**Issue by PhilipSkinner** [in2core/screenportsdk#3]
## Expected Behaviour

Can capture the current output shown either by accessing a method on the device, or by being able to use ImageRenderer (https://developer.apple.com/documentation/swiftui/imagerenderer).

This is the first time I have attempted to use ImageRenderer to capture a view, it is possible that I am doing this incorrectly. I have attempted this with other views and they work (see example below).

## Actual Behaviour

There is no method to capture the current frame as an image.

When using ImageRenderer or UIGraphicsImageRenderer the image property is always null.

## Steps to reproduce the problem

Code for ImageRenderer:

```
import ScreenPortSDK
import SwiftUI

struct DeviceStreamView: View {
    @ObservedObject
    var device: Device
    
    @State
    private var connectionType: ConnectionType = .auto
    
    @Environment(\.displayScale) var displayScale
    @State private var renderedImage = Image(systemName: "photo")
    
    var body: some View {
        VStack {
            renderedImage
            
            Button("Capture Video") {
                render_video()
            }
            
            Button("Capture Other") {
                render_example()
            }
        }
    }
    
    @MainActor func render_video() {
        let renderer = ImageRenderer(content: VideoView(device: device, connectionType: connectionType))
        renderer.scale = displayScale
        
        if let uiImage = renderer.uiImage {
            renderedImage = Image(uiImage: uiImage)
        } else {
            renderedImage = Image(systemName: "photo")
        }
    }
    
    @MainActor func render_example() {
        let renderer = ImageRenderer(content: VStack {
            Text("Hello world!")
        })
        renderer.scale = displayScale

        if let uiImage = renderer.uiImage {
            renderedImage = Image(uiImage: uiImage)
        } else {
            renderedImage = Image(systemName: "photo")
        }
    }
}

```

**Comment by michal-tomlein** [comment]
`ImageRenderer` might not work for capturing Metal layers. Either way, rather than capturing the scaled view itself, this would best be done by capturing at full resolution from our rendering pipeline, so I’m filing this under feature requests.

**Comment by PhilipSkinner** [comment]
Thanks! I've got a horrendous workaround for the time being - capture a whole device screenshot and crop it - which I can use until this is ready.

**Comment by michal-tomlein** [comment]
This functionality is now available both in `VideoView` (see demo project) and `VideoViewController` (`renderImage()` function).

**Comment by PhilipSkinner** [comment]
I've used this new functionality and it works great! I haven't had any issues, many thanks for adding it.
