### ISSUE TITLE
Ability to apply CIFilters

### ISSUE THREAD

**Issue by PhilipSkinner** [in2core/screenportsdk#5]
The ability to apply core image filters to the video stream. It should be possible to apply 1 or more filters in a specific order.

**Comment by michal-tomlein** [comment]
This is now available and the demo project has been updated with an example showing how to apply filters.

**Comment by PhilipSkinner** [comment]
This works really well, I've already got a collection of filters being applied to the video output from my ScreenPort. Thank you for adding this feature!
